COGNITO_CLIENT_ID: !Ref UserPoolClient
COGNITO_CLIENT_SECRET: !GetAtt UserPoolClient.ClientSecret
COGNITO_POOL_ID: !Ref UserPool
MAIN_TABLE_NAME: !Ref MainTable
MEALS_BUCKET: !Ref MealsBucket
MEALS_CDN_DOMAIN_NAME: !GetAtt MealsBucketCDN.DomainName
PROFILES_BUCKET: !Ref ProfilesBucket
PROFILES_CDN_DOMAIN_NAME: !GetAtt ProfilesBucketCDN.DomainName
MEALS_QUEUE_URL: !Ref MealsQueue
MENUS_QUEUE_URL: !Ref MenusQueue
OPENAI_API_KEY: ${env:OPENAI_API_KEY}
