COGNITO_CLIENT_ID: !Ref UserPoolClient
COGNITO_CLIENT_SECRET: !GetAtt UserPoolClient.ClientSecret
COGNITO_POOL_ID: !Ref UserPool
MAIN_TABLE_NAME: !Ref MainTable
MEALS_BUCKET: !Ref MealsBucket
MEALS_CDN_DOMAIN_NAME: !GetAtt MealsBucketCDN.DomainName
